const compoundFormulas = {
    water: 'H₂O',
    carbon_dioxide: 'CO₂',
    oxygen: 'O₂',
    hydrogen: 'H₂',
    methane: 'CH₄',
    ammonia: 'NH₃',
    sulfuric_acid: 'H₂SO₄',
    glucose: 'C₆H₁₂O₆',
    ethanol: 'C₂H₅OH',
    sodium_chloride: 'NaCl',
    potassium_hydroxide: 'KOH',
    calcium_carbonate: 'CaCO₃',
    urea: 'CO(NH₂)₂',
    sodium_bicarbonate: 'NaHCO₃',
    magnesium_sulfate: 'MgSO₄',
    sodium_hydroxide: 'NaOH',
    calcium_hydroxide: 'Ca(OH)₂',
    phosphoric_acid: 'H₃PO₄',
    potassium_chloride: 'KCl',
    aluminum_sulfate: 'Al₂(SO₄)₃',
    copper_sulfate: 'CuSO₄',
    zinc_sulfate: 'ZnSO₄',
    iron_oxide: 'Fe₂O₃',
    magnesium_oxide: 'MgO',
    calcium_phosphate: 'Ca₃(PO₄)₂',
    lead_nitrate: 'Pb(NO₃)₂',
    silver_nitrate: 'AgNO₃',
    sodium_thiosulfate: 'Na₂S₂O₃',
    potassium_iodide: 'KI',
    ammonium_chloride: 'NH₄Cl',
    sodium_chlorate: 'NaClO₃',
    boron_trifluoride: 'BF₃',
    chromium_oxide: 'Cr₂O₃',
    lithium_carbonate: 'Li₂CO₃',
    magnesium_carbonate: 'MgCO₃',
    iron_sulfate: 'FeSO₄',
    calcium_sulfate: 'CaSO₄',
    sodium_sulfate: 'Na₂SO₄',
    potassium_sulfate: 'K₂SO₄',
    nitrogen_dioxide: 'NO₂',
    sodium_nitrate: 'NaNO₃',
    calcium_nitrate: 'Ca(NO₃)₂',
    potassium_nitrate: 'KNO₃',
    sulfur_dioxide: 'SO₂',
    aluminum_oxide: 'Al₂O₃',
    potassium_perchlorate: 'KClO₄',
    magnesium_hydroxide: 'Mg(OH)₂',
    zinc_oxide: 'ZnO',
    calcium_chloride: 'CaCl₂',
    sodium_oxide: 'Na₂O',
    chlorine_gas: 'Cl₂',
    potassium_bromide: 'KBr',
    sodium_chloride: 'NaCl',
    nickel_sulfate: 'NiSO₄',
    potassium_sulfide: 'K₂S',
    sodium_iodide: 'NaI',
    iron_chloride: 'FeCl₃',
    sodium_phosphate: 'Na₃PO₄',
    copper_chloride: 'CuCl₂',
    calcium_sulfide: 'CaS',
    barium_hydroxide: 'Ba(OH)₂',
    iron_phosphate: 'FePO₄',
    manganese_dioxide: 'MnO₂',
    barium_nitrate: 'Ba(NO₃)₂',
    potassium_chromate: 'K₂CrO₄',
    potassium_dichromate: 'K₂Cr₂O₇',
    sodium_hydrogen_carbonate: 'NaHCO₃',
    calcium_carbonate: 'CaCO₃',
    sodium_sulfide: 'Na₂S',
    magnesium_chloride: 'MgCl₂',
    sodium_chloride: 'NaCl',
    aluminum_chloride: 'AlCl₃',
    potassium_hydrogen_phthalate: 'KHC₈H₄O₄',
    iron_sulfide: 'FeS',
    ammonium_sulfate: 'NH₄)₂SO₄',
    silver_chloride: 'AgCl',
    zinc_chloride: 'ZnCl₂',
    copper_oxide: 'CuO',
    calcium_phosphate: 'Ca₃(PO₄)₂',
    boric_acid: 'H₃BO₃',
    nickel_chloride: 'NiCl₂',
    manganese_chloride: 'MnCl₂',
    sodium_chlorate: 'NaClO₃',
    lithium_hydroxide: 'LiOH',
    sulfuric_acid: 'H₂SO₄',
    hydrochloric_acid: 'HCl',
    nitric_acid: 'HNO₃',
    potassium_chloride: 'KCl',
    calcium_oxide: 'CaO',
    magnesium_sulfate: 'MgSO₄',
    lithium_carbonate: 'Li₂CO₃',
    strontium_hydroxide: 'Sr(OH)₂',
    potassium_sulfate: 'K₂SO₄',
    potassium_nitrite: 'KNO₂',
    alum: 'KAl(SO₄)₂·12H₂O',
    borax: 'Na₂B₄O₇·10H₂O',
    oleum: 'H₂SO₄·xSO₃',
    caustic_soda: 'NaOH',
    quick_lime: 'CaO',
    sulfurous_acid: 'H₂SO₃',
    rock_salt: 'NaCl',
    soda_ash: 'Na₂CO₃',
    slaked_lime: 'Ca(OH)₂',
    leadstone: 'PbS',
    bauxite: 'Al₂O₃·2H₂O',
    magnesite: 'MgCO₃',
    sandhur: 'SiO₂',
      carbon: 'C',             
      nitrogen: 'N',           
      oxygen_gas: 'O₂',       
      sugar: 'C₆H₁₂O₆',        
      sulfur: 'S',           
      phosphorus: 'P',         
      chlorine: 'Cl',          
      potassium: 'K',          
      sodium: 'Na',            
      calcium: 'Ca',           
      magnesium: 'Mg',        
      iron: 'Fe',              
      zinc: 'Zn',             
      copper: 'Cu',            
      nickel: 'Ni',            
      aluminum: 'Al',         
      barium: 'Ba',           
      manganese: 'Mn',       
      iodine: 'I',            
      bromine: 'Br',           
      lithium: 'Li',          
  };  

  
  const compoundInput = document.getElementById('compound-input');
  const findFormulaBtn = document.getElementById('find-formula');
  const resultDiv = document.getElementById('result');
  
  const findFormula = () => {
    const compoundName = compoundInput.value.trim().toLowerCase().replace(/\s+/g, '_');
    if (compoundFormulas[compoundName]) {
      resultDiv.innerHTML = `<strong>Formula:</strong> ${compoundFormulas[compoundName]}`;
    } else {
      resultDiv.innerHTML = `<span style="color: red;">Compound not found. Please try another!</span>`;
    }
  };
  findFormulaBtn.addEventListener('click', findFormula);
  compoundInput.addEventListener('keyup', (e) => {
    if (e.key === 'Enter') {
      findFormula();
    }
  });
  